### ISSUE TITLE
thread 'main' panicked at 'Non-standard address'

### ISSUE THREAD

**Issue by sunnyboy00** [MathNya/umya-spreadsheet#114]
thread 'main' panicked at 'Non-standard address',   
umya-spreadsheet-0.9.1/src/structs/address.rs:41:13

**Comment by sunnyboy00** [comment]
[test.zip](https://github.com/MathNya/umya-spreadsheet/files/10978670/test.zip)

upload the error file

**Comment by MathNya** [comment]
@sunnyboy00 
Thank you for your report.
We will investigate the cause.

**Comment by sunnyboy00** [comment]
Thank you very much
