### ISSUE TITLE
breaking change

### ISSUE THREAD

**Issue by cstkingkey** [MathNya/umya-spreadsheet#115]
ef3f99bee47115285dba223e35691f6933e196af and following commits change the logic of set_value_from_string, which break code relying on it and cause data loss.

Please rename the functions to avoid it.

**Comment by cstkingkey** [comment]
@john-dc252

**Comment by john-dc252** [comment]
![image](https://user-images.githubusercontent.com/46738260/224607734-bc562f7c-c66e-4e85-ad96-8d6666aad332.png)
Hello @cstkingkey,

Is this the change that you mean?
Do you mean that we should rename `set_value_from_string` to something else?
Or should we rename it back to `set_value`?

**Comment by cstkingkey** [comment]
> ![image](https://user-images.githubusercontent.com/46738260/224607734-bc562f7c-c66e-4e85-ad96-8d6666aad332.png) Hello @cstkingkey,
> 
> Is this the change that you mean? Do you mean that we should rename `set_value_from_string` to something else? Or should we rename it back to `set_value`?

set_value_from_string is renamed to set_value_string, while set_value is renamed to set_value_from_string. I use set_value_from_string, so it leads to data loss.

since version 0.9 is published, both functions need to be renamed to different names to force downstream developers to use correct functions. And I'm afraid that all relevant functions need a review.

**Comment by john-dc252** [comment]
Hello @cstkingkey ,

While I mentioned the changes I made in my PR, they are not mentioned in the readme change log for 0.9.

Would updating the readme to mention this change not be enough?

**Comment by cstkingkey** [comment]
> Hello @cstkingkey ,
> 
> While I did mention these changes in my PR, they are not mentioned in the readme change log for 0.9.
> 
> Would updating the readme to mention this change not be enough?

It would be better to change the names. It can be enough to mention this change in the readme. 
Either is acceptable to me, as I already paid the cost.

**Comment by john-dc252** [comment]
@MathNya

**Comment by MathNya** [comment]
@john-dc252
@cstkingkey 
We have checked the situation.
I will try to handle this by renaming set_value_from_string to set_value.
This is more backward-compatible and less uncomfortable with the name set_value.
