### ISSUE TITLE
Tables are not supported

### ISSUE THREAD

**Issue by vonkruel** [MathNya/umya-spreadsheet#117]
My client's application requires support for reading and writing worksheet tables, and I've found this facility to be absent from the library.  I've spent some time familiarizing myself with Excel tables and the library code, and I'm just about ready to start coding for this feature.  Of course I will want this support to be integrated into the library, both to make it available to other users and to avoid the pain of maintaining a fork.  As I undertake this little project, I thought I should check in to see what the author(s) of this library think.  If you have any advice for me (or if you're against the idea for any reason) please do let me know.  Thanks!

**Comment by MathNya** [comment]
@vonkruel 
Thank you for your suggestion.
We were planning to put the table support on the back burner for the time being, so we would be very happy if you could implement it.
If you send us a PR, we will of course merge them.

The file structure of the umya-spreadsheet is based on this reference.
https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet?view=openxml-2.8.1

This is only for reference. It is not strict.
Parts that I think are redundant are omitted, and some parts are completely ignored for the sake of usability.

**Comment by vonkruel** [comment]
I finally got around to submitting the PR and it was accepted, so that's the end of this issue.
