### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by sunnyboy00** [MathNya/umya-spreadsheet#118]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', umya-spreadsheet/src/structs/vml/shape.rs:283:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', umya-spreadsheet/src/structs/drawing/spreadsheet/two_cell_anchor.rs:222:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by MathNya** [comment]
@sunnyboy00
Thank you for your report.
From the error, it seems that there is a problem when loading the image file.
If possible, please provide us with the Excel file in which the error occurred.

**Comment by sunnyboy00** [comment]
[test1.zip](https://github.com/MathNya/umya-spreadsheet/files/11200006/test1.zip)

 upload file

I think the unwrap（） function should not be  used

**Comment by MathNya** [comment]
Thank you for the files.
We were able to confirm the event here as well.
We will address this issue in the next version of the software.

**Comment by sunnyboy00** [comment]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', umya-spreadsheet/src/structs/vml/shape.rs:283:77

pls fix the same issue
