### ISSUE TITLE
Moving cell functionality

### ISSUE THREAD

**Issue by boseongkim32** [MathNya/umya-spreadsheet#125]
Hi, I had an idea for moving cell functionality, for which I tentatively made a function at the end of spreadsheet.rs in structs. 
If I wanted to move cells A1:D6 by 2 rows and 3 columns, it would shift all the values by 3 cells to the right, 2 rows down. 
I was wondering if it would be a good idea to: 

check whether the coordinates to move are within range 
then iterate through the cells, collecting the information
repaste the information using set_value 

or something alone those lines. thanks! 

I also think it would be nice to have merge cell functionality in the future, which I would also love to contribute to

**Comment by MathNya** [comment]
@boseongkim32 
Thank you for your suggestion.
Moving cells and merging cells. I would love to adopt both.
I will try to implement them in the next few days.

**Comment by MathNya** [comment]
@boseongkim32 
I implemented move_range.
Please check it if you have time.
```rust
let range = "C5:F9";
let row = 12;
let column = 4;
book.get_sheet_by_name_mut("Sheet1").unwrap().move_range(range, &row, &column);
```

Also, merge_cells, but there was already a similar function.
```rust
book.get_sheet_by_name_mut("Sheet1").unwrap().add_merge_cells("A1:C5");
```

**Comment by boseongkim32** [comment]
Hi, yes move range works! I added a tiny test myself
