### ISSUE TITLE
Output number to String

### ISSUE THREAD

**Issue by ziyouwa** [MathNya/umya-spreadsheet#126]
let a = "000001".to_string(),

tyied these:
sheet.get_cell_mut("B1").set_value(format!("{:0>6}", a.b));  // only 1
sheet.get_cell_mut("B1").set_value(a.b.clone()); //only 1
sheet.get_cell_mut("B1").set_value(&a.b);  // only1

when output it to file, only  display 1.  How to display 000001 as txt?

**Comment by john-dc252** [comment]
you can use `set_value_string` instead of `set_value`

**Comment by ziyouwa** [comment]
> you can use `set_value_string` instead of `set_value`

Thanks!
