### ISSUE TITLE
Reading Cells W/ Shared Strings

### ISSUE THREAD

**Issue by IronicGambler** [MathNya/umya-spreadsheet#128]
Hi, this is a fantastic crate and I want to say thank you to all of the contributors.

I'm having one small issue when it comes to reading cells with a formula that references  a shared string.

To reproduce the bug, i created this workbook: [wb_with_shared_strings.xlsx](https://github.com/MathNya/umya-spreadsheet/files/12448759/wb_with_shared_strings.xlsx) its just a .xlsx file with two sheets. The first sheet is called "Sheet To Read From", the cells in range A1:A6 contain a formula which reference the second sheet ("Cells Referenced By Formulas").  The values within range A1:A6 of the "Cells Referenced By Formulas" sheet are 
'      `Column A`
'- + --
`1` | Column Header
`2` | 11
`3` | 22
`4` | ABCdef
`5` | ABCdef
`6` | ABCdef

and in the first sheet, (the "Sheet To Read From"), below are the formulas which reference the above range:
'      `Column A`
'- + --
`1` | Column Header
`2` | ='Cells Referenced By Formulas'!A2
`3` | ='Cells Referenced By Formulas'!A3
`4` | ='Cells Referenced By Formulas'!A4
`5` | ='Cells Referenced By Formulas'!A5
`6` | ='Cells Referenced By Formulas'!A6

When I try to read this file, the numeric values work no problem, but the strings can't be read. I believe this is due to the cell contents being a shared string, I went through the source code, and was not able to figure the exact source of the problem (my apologies). But, if you use the .xlsx file i linked above with this code you will see the problem:
```rust
#[cfg(test)]
mod tests {
    use umya_spreadsheet;
    use umya_spreadsheet::Spreadsheet;

    const SHEET_NAME: &str = "Sheet To Read From";
    const A_RANDOM_STRING: &str = "ABCdef";

    #[test]
    fn read_wb_with_shared_strings() {
        let workbook: Spreadsheet = umya_spreadsheet::reader::xlsx::read("./wb_with_shared_strings.xlsx").unwrap();
        let sheet_to_read = workbook.get_sheet_by_name(SHEET_NAME).unwrap();

        // these numeric values work no problem
        // note: i used the `get_formatted_values` here, but same applies with `get_value` type fns
        let cell_a2 = sheet_to_read.get_formatted_value("A2");
        let cell_a3 = sheet_to_read.get_formatted_value("A3");
        assert_eq!(cell_a2, "11"); 
        assert_eq!(cell_a3, "22");

        // but the cells with shared strings are read as null values
        let cell_a4 = sheet_to_read.get_cell("A4").unwrap().get_raw_value();
        // to show this, this should fail, because cellA4's value should be "ABCdef"
        assert_eq!(cell_a4, &umya_spreadsheet::CellRawValue::Null);  // <-- this test does pass, but shouldn't

        // both cell A4 and A5's value are "ABCdef", so this test should pass, but instead fails
        let cell_a5 = sheet_to_read.get_formatted_value("A5");
        assert_eq!(cell_a5, "ABCdef"); // <-- this test will fail
    }
}
```

It is worth noting, the below test *does* work (in the second test I create a workbook with 1 sheet, save it, and read it)
```rust
    #[test]
    fn from_a_new_file_in_same_sheet() {
        
        // create a new workbook and populate it
        let mut workbook = umya_spreadsheet::new_file();
        let _ = workbook.new_sheet(SHEET_NAME);
        for row_num in 1..6 {
            let cell_addr = format!("A{row_num}");
            
            workbook.get_sheet_by_name_mut(SHEET_NAME).unwrap().get_cell_mut(cell_addr).set_value(A_RANDOM_STRING);
        }

        // save the file
        let fpath = "./a_new_wb.xlsx";
        let _ = umya_spreadsheet::writer::xlsx::write(&workbook, fpath);

        // reopen the file and read it's contents
        let newly_created_wb = umya_spreadsheet::reader::xlsx::read(fpath).unwrap();
        let sheet_to_read = newly_created_wb.get_sheet_by_name(SHEET_NAME).unwrap();

        let cell_a2 = sheet_to_read.get_formatted_value("A2");
        assert_eq!(cell_a2, A_RANDOM_STRING);
        let cell_a3 = sheet_to_read.get_formatted_value("A3");
        assert_eq!(cell_a3, A_RANDOM_STRING);
    }   
```

Please let me know if you have any questions, I'd be happy to provide more details!

**Comment by MathNya** [comment]
@IronicGambler 
Thank you for your report.
We will investigate and make modifications to the issue at hand.
If any questions arise, we will contact you.
Thank you very much for your cooperation.

**Comment by MathNya** [comment]
@IronicGambler 
The program has been modified.
Please check it.

**Comment by IronicGambler** [comment]
Hi,

Thank you, i went over it and the library worked- thank you for all of your help, you are the best!
