### ISSUE TITLE
xml escape character "&" is corrupting sheetname on write

### ISSUE THREAD

**Issue by agentjill** [MathNya/umya-spreadsheet#143]
in `book.get_sheet_by_name_mut("Sheet2").unwrap().get_cell_mut("A1").set_value("TEST1");` 

if the sheet name contains xml escape characters for example say `Alice&Bob` then it is not detecting the `Worksheet`.

On inspection the  ''Alice&Bob'' is being processed as `Alice&amp;Bob`, that would mean that xml escape character `&amp;` is not properly read as `&`.

calling sheet by `Alice&amp;Bob `is saving the workbook as `Alice&&amp;amp;Bob`

**Comment by MathNya** [comment]
@agentjill
Thank you for your report.
We will address this in the next version update.

**Comment by agentjill** [comment]
This was addressed in #145.
