### ISSUE TITLE
writer is corrupting the protected sheets 

### ISSUE THREAD

**Issue by agentjill** [MathNya/umya-spreadsheet#146]
when using the `writer::xlsx::write(&book, file_path.as_ref())` it is not preserving the protections already placed in the file.

For example, a workbook has a sheet (say 'A') where some of the range is protected. When writing to other sheets(say 'B'), the sheet 'A' is losing its protections placed.

**Comment by MathNya** [comment]
@agentjill 
Protection was not supported.
It is probably easy to implement and we will try to support it soon.
