### ISSUE TITLE
insert_and_remove_cells incorrect output

### ISSUE THREAD

**Issue by meettitan** [MathNya/umya-spreadsheet#155]
The [`insert_and_remove_cells`](https://github.com/MathNya/umya-spreadsheet/blob/master/tests/integration_test.rs#L724) test is non deterministically removing and shuffling cells.

One run of the test yields:
![Screenshot from 2023-12-02 19-52-12](https://github.com/MathNya/umya-spreadsheet/assets/12808841/cad5043b-22e4-423b-914c-0ab9caa4e52a)

while another run yields: 
![Screenshot from 2023-12-02 19-52-49](https://github.com/MathNya/umya-spreadsheet/assets/12808841/301352e7-4b3c-4cc8-aa28-ee1a8e8cd7e6)

Neither of which seem correct.

**Comment by MathNya** [comment]
@meettitan 
We were able to identify the cause of the malfunction.
We will release a corrected version as soon as possible.

**Comment by meettitan** [comment]
Very nice, you guys beat me to the solution! I had only gotten to the map collisions in `Cells::rebuild_map()`.

I look forward to seeing your solution, and contributing in the future. Thanks again guys!

**Comment by MathNya** [comment]
@meettitan 
The latest version has been released.
Please check it out.

**Comment by meettitan** [comment]
@MathNya
I have looked into it and was testing the solution. I think some style formatting may still be incorrect, but I haven't had time to fully test. The core issue is resolved, I'll mark it as such; and if I can reproduce the styling issue concisely, I'll open a separate issue. Thanks again for your time.
