### ISSUE TITLE
double_value.rs bug

### ISSUE THREAD

**Issue by h4cnull** [MathNya/umya-spreadsheet#16]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Empty }', D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\structs\double_value.rs:28:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src\main.rs:483:34

**Comment by h4cnull** [comment]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Empty }', D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\structs\double_value.rs:28:41
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c390d69a615f095208ac94841f3310268521b2ee\/library\std\src\panicking.rs:495
   1: core::panicking::panic_fmt
             at /rustc/c390d69a615f095208ac94841f3310268521b2ee\/library\core\src\panicking.rs:106
   2: core::result::unwrap_failed
             at /rustc/c390d69a615f095208ac94841f3310268521b2ee\/library\core\src\result.rs:1617
   3: enum$<core::result::Result<f64,core::num::dec2flt::ParseFloatError> >::unwrap<f64,core::num::dec2flt::ParseFloatError>
             at /rustc/c390d69a615f095208ac94841f3310268521b2ee\library\core\src\result.rs:1299
   4: umya_spreadsheet::structs::double_value::DoubleValue::set_value_string<alloc::string::String>
             at D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\structs\double_value.rs:28
   5: umya_spreadsheet::structs::row::Row::set_attributes
             at D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\structs\row.rs:152
   6: umya_spreadsheet::reader::xlsx::worksheet::read
             at D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\reader\xlsx\worksheet.rs:76
   7: umya_spreadsheet::reader::xlsx::read
             at D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\umya-spreadsheet-0.4.0\src\reader\xlsx.rs:105
   8: ratel::result_handler::generator$0
             at .\src\main.rs:224
   9: core::future::from_generator::impl$1::poll<ratel::result_handler::generator$0>
             at /rustc/c390d69a615f095208ac94841f3310268521b2ee\library\core\src\future\mod.rs:80
  10: async_std::task::builder::impl$1::poll::closure$0<core::future::from_generator::GenFuture<ratel::result_handler::generator$0> >       
             at D:\RUST\cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.10.0\src\task\builder.rs:199
  11: async_std::task::task_locals_wrapper::impl$0::set_current::closure$0<async_std::task::builder::impl$1::poll::closure$0,enum$<core::task::poll::Poll<tuple$<> > > >

**Comment by h4cnull** [comment]
match umya_spreadsheet::reader::xlsx::read(path) {
            Ok(book) => {
                let sheet1 = book.get_sheet(0).unwrap_or_else(|e|{
                    println!("{}",e);
                    std::process::exit(-1);
                });
                let mut row = 2;
                let host_col = 2;
                let port_col = 4;
                loop {
                    let host = sheet1.get_cell_value_by_column_and_row(host_col, row).get_value();
                    if host == "" {
                        break;
                    }
                    println!("{}",host);
                    let port = sheet1.get_cell_value_by_column_and_row(port_col, row).get_value();
                    let host_port = format!("{}:{} ",host,port);
                    println!("{}",host_port);
                    excludes.push_str(&host_port);
                    row += 1;
                }
                
            },
            _ => {}
        };

**Comment by MathNya** [comment]
Thank you for your report.
We will investigate the issue and fix the program as soon as we find the cause.

**Comment by MathNya** [comment]
Fixed a bug.
Please get the latest version and check again.
