### ISSUE TITLE
Valid definedName containing list of cells or ranges panics

### ISSUE THREAD

**Issue by joshimi** [MathNya/umya-spreadsheet#162]
Excel supports `definedName` format of a list of comma separated addresses (cells or ranges).
Reading such an Excel file panics on "Non-standard address".

**Comment by joshimi** [comment]
[test.xlsx](https://github.com/MathNya/umya-spreadsheet/files/13696886/test.xlsx)

**Comment by MathNya** [comment]
@joshimi 
Thank you for contacting us.
We will investigate and make the necessary changes.
