### ISSUE TITLE
Get Picture cropping info

### ISSUE THREAD

**Issue by schungx** [MathNya/umya-spreadsheet#164]
I have a spreadsheet with images that have been cropped.

I can see the following information regarding the cropping:

`Picture.blip_fill -> BlipFill.source_rectangle -> SourceRectangle { t, l, r, b }`

The measurements within `SourceRectangle` are all strings, which store a simple text representation of numbers.

How do I calculate the cropping offsets from this?  Is there any documentation I can look up?

I can see that `t` = top, `l` = left, `r` = right and `b` = bottom...  The numbers (represented as strings) do not quite match anything though...

**Comment by MathNya** [comment]
@schungx 
Thank you for contacting us.
Sorry, I don't have the specs on the SourceRectangle values.
According to this page, it seems to be a percentage.
http://officeopenxml.com/drwPic-tile.php

**Comment by schungx** [comment]
Thanks a great deal.

Just knowing it may be a percentage already makes loads of sense.
