### ISSUE TITLE
Unable to read custom properties defined at excel

### ISSUE THREAD

**Issue by BharathIO** [MathNya/umya-spreadsheet#173]
Hi,
  I tried to read custom properties defined at excel. But i am getting empty Vector as result. I did set one text variable and one number type variable and i am not able to get both the values. Can someone please help me how to read them?

i have a usecase to write a new value to excel too.

**Comment by BharathIO** [comment]
I am using below code to read properties.

```java
pub fn get_custom_properties(&self) -> &Vec<String> {
        &self.custom_properties
    }
```

**Comment by MathNya** [comment]
@BharathIO 
Thank you for contacting us.
The current version did not support custom properties.
get_custom_properties() returns empty.
set_custom_properties() does not refer to it when saving.

We will consider supporting this in the next version update.

**Comment by BharathIO** [comment]
Oh ok, when can we expect next version with custom properties support?

**Comment by BharathIO** [comment]
Thanks. Hope we will get support to read and write custom properties.

**Comment by MathNya** [comment]
@BharathIO 
The latest version has been released. Please check it out.

**Comment by BharathIO** [comment]
Thanks, it is working.
