### ISSUE TITLE
The set_workbook_password method seems to be invalid

### ISSUE THREAD

**Issue by shijunti19** [MathNya/umya-spreadsheet#176]
The set_workbook_password method seems to be invalid, and the generated document remains unchanged
book_lock.xlsx
![image](https://github.com/MathNya/umya-spreadsheet/assets/5392211/702459d6-f847-426a-a71c-5b22a9e3412a)
![image](https://github.com/MathNya/umya-spreadsheet/assets/5392211/e2518655-13d8-41ab-be8a-669f348539e0)
![image](https://github.com/MathNya/umya-spreadsheet/assets/5392211/8bc82dda-9cf9-4aee-a1e3-76b63452ca0b)

office2019

If the settings are normal, it should be like this：
![image](https://github.com/MathNya/umya-spreadsheet/assets/5392211/eb5ac395-759a-4c43-aa4d-23cee9bad8d1)

**Comment by shijunti19** [comment]
I seem to have made a mistake, but it really didn't work

**Comment by MathNya** [comment]
@shijunti19 
Using write_with_password will do what you want.
```rust
    let path = std::path::Path::new("./tests/test_files/aaa.xlsx");
    let mut book = umya_spreadsheet::reader::xlsx::read(path).unwrap();
    let path = std::path::Path::new("./tests/result_files/bbb_password.xlsx");
    let _ = umya_spreadsheet::writer::xlsx::write_with_password(&book, path, "password");
```

set_workbook_password corresponds to the function shown in the following figure in Excel.
![image](https://github.com/MathNya/umya-spreadsheet/assets/70010127/760003a2-83f9-4add-90df-b164c3767268)
