### ISSUE TITLE
CellCoordinates should implement clone features

### ISSUE THREAD

**Issue by shijunti19** [MathNya/umya-spreadsheet#177]
use umya_spreadsheet::helper::coordinate::CellCoordinates;

CellCoordinates are used in many places, and I think they should have clone features

![image](https://github.com/MathNya/umya-spreadsheet/assets/5392211/04a0ac37-c533-4b22-a7d7-4e12aa077b56)
He should be asked to reuse it

**Comment by MathNya** [comment]
@shijunti19 
This will be addressed in the next version update.

**Comment by MathNya** [comment]
@shijunti19 
We have released 1.2.1 which fixes this problem.
Please check it out.
