### ISSUE TITLE
Chart example

### ISSUE THREAD

**Issue by danielstuart14** [MathNya/umya-spreadsheet#18]
Thanks for this awesome library!
Could you please add a chart example to the readme? I guess a simple linechart would already be enough to understand the basic functionality.

Thanks

**Comment by MathNya** [comment]
Thanks for the suggestion.
We will work on it in the next update.
(Currently, adding a chart requires a complicated procedure. 
We will prepare a function to easily achieve this and guide you through it).

**Comment by MathNya** [comment]
We have prepared a function to add a chart.
Please check the README.md for details.

**Comment by danielstuart14** [comment]
awesome, thank you so much!
