### ISSUE TITLE
Wasm build getrandom dependency.

### ISSUE THREAD

**Issue by taylorh140** [MathNya/umya-spreadsheet#183]
Im trying to build for wasm and getrandom dependency is making it difficult. I'm curious what its used for or if there is a way to exclude it from the build?

**Comment by MathNya** [comment]
@taylorh140 
Thank you for contacting us.
getrandom is used to set passwords for files.
If you do not need this feature, you can exclude it.

**Comment by taylorh140** [comment]
Ya i figured out that I can use a feature to prevent some issues. particularly:

cargo.toml
```toml
getrandom = { version = "0.2.12", features = ["custom"] }
```

and
```rust
use getrandom::register_custom_getrandom;
use getrandom::Error;

// Some application-specific error code
pub fn always_fail(_buf: &mut [u8]) -> Result<(), Error> {
    Ok(())
}


register_custom_getrandom!(always_fail);
```

**Comment by taylorh140** [comment]
@MathNya 
> @taylorh140 Thank you for contacting us. getrandom is used to set passwords for files. If you do not need this feature, you can exclude it.

Is there a easier way to exclude this?

**Comment by MathNya** [comment]
getrandom is only used in src.helper.crypt.rs.
I think we can remove this class.

I would also like to address the problem with getrandom when building for wasm.
I will replace it with an alternative package in the next version.
