### ISSUE TITLE
does not read a formula like A1=A2=A3 from a file

### ISSUE THREAD

**Issue by mjhmjhgkmj** [MathNya/umya-spreadsheet#185]
![image](https://github.com/MathNya/umya-spreadsheet/assets/45330841/dc530f84-c519-4cff-8f1b-61c9af9475f4)

Excel is working with formulas with this format, but umya-spreadsheet says that:

cell.is_formula() is false

**Comment by mjhmjhgkmj** [comment]
[issue_185.xlsx](https://github.com/MathNya/umya-spreadsheet/files/14855132/issue_185.xlsx)

**Comment by MathNya** [comment]
Thank you for your report.
We will address this in the next version update.
