### ISSUE TITLE
Auto width

### ISSUE THREAD

**Issue by MGlolenstine** [MathNya/umya-spreadsheet#20]
I'm generating XLSX files to be ready for printing.
Whenever the file is generated, the cell width is sometimes smaller than the content, so the cells overlap.

Is there a way to change the width of a column to fit the widest cell?

**Comment by MathNya** [comment]
Thank you for contacting us.
We will investigate the cause and contact you as soon as we find out.
We will also update the program if necessary.

**Comment by MathNya** [comment]
We have provided two means of setting the column width.
Please try them after getting the latest version.
1. Auto width
`worksheet.get_column_dimension_mut("A).set_auto_width(true);`
2. Manual
`worksheet.get_column_dimension_mut("A").set_width(60f64);`

**Comment by MGlolenstine** [comment]
I just tested out the new `set_auto_width` function and it works great!
Thanks for the quick response and implementation!
