### ISSUE TITLE
Feature request: a way to force formula recalculation in LibreOffice

### ISSUE THREAD

**Issue by Expurple** [MathNya/umya-spreadsheet#201]
I would like to see something like [worksheet.set_formula_result_default("")](https://docs.rs/rust_xlsxwriter/0.68.0/rust_xlsxwriter/worksheet/struct.Worksheet.html#method.set_formula_result_default) from `rust_xlsxwriter`. Maybe this feature already exists, but I couldn't find it in the documentation.

**Comment by MathNya** [comment]
@Expurple 
Yes, sir.
It will probably be easy to implement and will be addressed in the next version update.

**Comment by MathNya** [comment]
Oh, sorry.
We have released the latest version, but just now we realized that it is not supported here.
We will fix it soon.

**Comment by agentjill** [comment]
> Oh, sorry. We have released the latest version, but just now we realized that it is not supported here. We will fix it soon.

@MathNya, kindly also update github releases for newer version

**Comment by MathNya** [comment]
@Expurple 
The latest version is now available.
Please use this function.
```rust    
let path = std::path::Path::new("./tests/test_files/issue_201.xlsx");
let mut book = umya_spreadsheet::reader::xlsx::read(path).unwrap();
let mut cell = book.get_sheet_mut(&0).unwrap().get_cell_mut("B1");
cell.set_formula_result_default("");
```

**Comment by Expurple** [comment]
Technically, this is equivalent to per-cell [set_formula_result](https://docs.rs/rust_xlsxwriter/0.68.0/rust_xlsxwriter/worksheet/struct.Worksheet.html#method.set_formula_result), rather than global per-sheet [set_formula_result_default](https://docs.rs/rust_xlsxwriter/0.68.0/rust_xlsxwriter/worksheet/struct.Worksheet.html#method.set_formula_result_default). But this should be enough for my use case, thank you. I'll close the issue and let someone else reopen it or open a new one, if they really need a global default.
