### ISSUE TITLE
vertical alignment has no bottom

### ISSUE THREAD

**Issue by taylorh140** [MathNya/umya-spreadsheet#210]
i have some code to grab the horizontal and vertical alignments :
```rust
   if let Some(varA) = cell.get_style().get_alignment() {
      tmp_cell_data["alignment"] = json!({
          "horizontal": varA.get_horizontal().get_value_string(),
          "vertical": varA.get_vertical().get_value_string(),
          "rot": varA.get_text_rotation(),
          "wrap": varA.get_wrap_text(),
      })
   }
```
given the following doc:
![image](https://github.com/user-attachments/assets/11727b2a-2176-481c-86ec-d2390673206c)
I get the following for vertical alignment:

```
top *A*
top *B*
top G
top H
top D
center M
none
none
top I
top J
none
center F
top C
top N
top K
top E
```
this is problematic given that most cells are bottom aligned.

**Comment by agentjill** [comment]
@taylorh140, Looking at repo code it looks like default value of the `VerticalAlignmentValues` is set to as `Top` Variant. It is my guess that there is a problem reading and storing it in `Alignment` struct, the `get_vertical()` would yield its default value which happens to be `Top`.

**Comment by taylorh140** [comment]
@agentjill Any suggestions on how to work around this? or maybe I need to rebuild or PR with Bottom as default?

**Comment by agentjill** [comment]
> or maybe I need to rebuild or PR with Bottom as default?

I dont think that is a good idea. The default behaviour is correct to be `Top`. The problem may be due to reading the alignment. I think it may be addressed in next version (may be).

**Comment by MathNya** [comment]
Thank you for your report.
Hmmm, agentjill is right, there may be something wrong with reading the alignment.
I will investigate.

**Comment by MathNya** [comment]
The latest version has been released.
Please check to see if any problems have been resolved.

**Comment by taylorh140** [comment]
This seems to be resolved!
