### ISSUE TITLE
Formula in Table Not Working

### ISSUE THREAD

**Issue by WilliamTCarroll** [MathNya/umya-spreadsheet#215]
Hello!  Thank you for this awesome crate.  I just have an issue I found.

When using Formulae inside of Tables that reference inside itself or even outside the table, the formula and table are marked as broken by Excel.

EX:
`=[@Column1]`
`=H4`

In either case, when opening the output, Excel asks you to "fix" the file, and then deletes the affected Table(s).

Table files below:
[table_in.xlsx](https://github.com/user-attachments/files/16444911/table_in.xlsx)
[table_out.xlsx](https://github.com/user-attachments/files/16444912/table_out.xlsx)

Please let me know if you have further questions, thank you!

**Comment by MathNya** [comment]
@WilliamTCarroll 
Thank you for your report.
We will proceed with our investigation.

**Comment by MathNya** [comment]
@WilliamTCarroll 
Fixed issue.
Please get the latest version and check it.

**Comment by WilliamTCarroll** [comment]
@MathNya thank you very much!  That works great!  I will let you know if I run into other issues.
