### ISSUE TITLE
Panic when reading Excel file

### ISSUE THREAD

**Issue by schungx** [MathNya/umya-spreadsheet#219]
The attached simplified file panics upon load.

[test-marker.xlsx](https://github.com/user-attachments/files/16723401/test-marker.xlsx)

`xdr:colOff` is trying to be parsed into `usize` but the actual value is `-1` which is negative...  So it choked.

Should the row/column offsets be signed?

**Comment by MathNya** [comment]
@schungx 
As you pointed out, i32 seems to be the correct answer for xdr:colOff, not usize.
Fixed.

**Comment by MathNya** [comment]
@schungx 
Fixed issue.
Please get the latest version and check it.

**Comment by schungx** [comment]
Thanks, will check it out.

However, it seems that, according to the standard, it can also be a string with a unit such as `12in`... So eventually I believe we'd bump into a file that has some weird value...

**Comment by schungx** [comment]
Works!  Closing.
