### ISSUE TITLE
Difference to calamine?

### ISSUE THREAD

**Issue by kangalioo** [MathNya/umya-spreadsheet#22]
Hey, this crate just popped up in my github explore page and it seems pretty similar to [calamine](https://github.com/tafia/calamine). What does this crate do differently?

Info about this would be nice to have in the README too

**Comment by MathNya** [comment]
Hi, kangalioo.

calamine is a read-only library.
umya-spreadsheet can be read, edited, and saved.
We will update the README in the next version update.

**Comment by MGlolenstine** [comment]
@kangalioo Calamine also only supports reading data as data and functions.
This crate also allows you to style it and draw graphs.

**Comment by MathNya** [comment]
README has been updated.
