### ISSUE TITLE
Add value to a new cell does not pick up the cell's style

### ISSUE THREAD

**Issue by schungx** [MathNya/umya-spreadsheet#220]
Now, when I set a value into an originally-blank cell, I understand that a new `Cell` record is created and inserted into the `cells` collection.

However, that `Cell` should pick up the style index of the cell in question.  Currently it doesn't, therefore setting a value into a blank cell will essentially erase all of that cell's styles.

I believe we should look up the style index of that cell, then copy it from the stylesheet by default if a new cell is created.

**Comment by schungx** [comment]
Test file:
[test.xlsx](https://github.com/user-attachments/files/16844143/test.xlsx)

![{C1FA2B4F-C481-432B-A583-0B14A5A3B6DF}](https://github.com/user-attachments/assets/12fc2b52-5399-4f4c-a7b2-2d46b992bb80)

Setting value:
[text1.xlsx](https://github.com/user-attachments/files/16844186/text1.xlsx)

![{CF148BB8-917F-40DF-A776-284700F67EDB}](https://github.com/user-attachments/assets/6d3b4ad4-82a5-492c-8fe9-75b69fb76a45)

**Comment by MathNya** [comment]
@schungx 
Thank you for your report.
We will investigate and make the necessary modifications.

**Comment by schungx** [comment]
I see in the code that setting a value automatically adds a `Cell` if one is not there.

However during the creation od that `Cell` it really should inspect the `cell_format` of the cell in question and copy the style from the index.

**Comment by MathNya** [comment]
The latest version has been released.
Please confirm that the problem has been fixed.
