### ISSUE TITLE
Formulas overwritten by the lazy value of the cell

### ISSUE THREAD

**Issue by oxabz** [MathNya/umya-spreadsheet#225]
It appears that formulas are overwritten by the default formula value in some cases. 

I looked a bit at the code and I found that when parsing the cell at the end of the `<v>` tag the parser doesn't check if the `<f>` element as already be encountered and just use the `Cell::set_value_string` type function which set the formula to `None`

I experimented with adding a check for the formula and used `set_formula_result_default` in case where a formula exists and my fix seems to work. But that said I'm not familiar with the codebase and it might break some other cases : 

```rust
// In src/structs/cell.rs

fn set_attributes</**/> (/**/) {
    // ...
    loop {
        match reader.read_event_into(&mut buf) {
            //...
            Ok(Event::End(ref e)) => match e.name().into_inner() {
                    b"v" => match type_value.as_str() {
                        _ if self.cell_value.is_formula() => {
                            self.set_formula_result_default(&string_value);
                        }
                        "str" => {
                            self.set_value_string(&string_value);
                        }
                        //...
                        _ => {}
                    },
                    // ...
                },
               //...
           }
     }
}
```

I've also seen the lazy value type and wonder if it could be related to this too.

**Comment by oxabz** [comment]
Here is a minimal file to reproduce the bug.

[min-bug-reproduction.xlsx](https://github.com/user-attachments/files/17025811/min-bug-reproduction.xlsx)

**Comment by MathNya** [comment]
@oxabz 
Thank you for your report.
We have checked and found a defect in the relevant section.
We will correct the problem based on the PR you received.

**Comment by oxabz** [comment]
I've checked the fix on my project. Everything seems to be working correctly.
Thanks for the swift answer. Keep up the great work!
