### ISSUE TITLE
In lazy read get_sheet panic

### ISSUE THREAD

**Issue by yorkz1994** [MathNya/umya-spreadsheet#227]
In lazy read, `get_sheet` function panics while `get_sheet_mut` is fine.

Could you please implement the same logic for `get_sheet` to avoid panic.
I.e. to do deserialization instead of assert.
```
pub fn get_sheet(&self, index: &usize) -> Option<&Worksheet> {
        self.work_sheet_collection
            .get(*index)
            .map(|v| {
                assert!(v.is_deserialized(),"This Worksheet is Not Deserialized. Please exec to read_sheet(&mut self, index: usize);");
                v
            })
    }
```
```
pub fn get_sheet_mut(&mut self, index: &usize) -> Option<&mut Worksheet> {
        let shared_string_table = self.get_shared_string_table();
        let stylesheet = self.get_stylesheet().clone();
        self.work_sheet_collection.get_mut(*index).map(|v| {
            raw_to_deserialize_by_worksheet(v, shared_string_table, &stylesheet);
            v
        })
    }
```

**Comment by MathNya** [comment]
@yorkz1994 
Thank you for contacting us.
This one, however, is technically difficult.
To deserialize, it needs to be mutable itself.
Therefore, get_sheet() before deserialization is a panic.
Please execute read_sheet(); first, then get_sheet().

If you just want to reference cell values, you can do so without deserialization;
try get_lazy_read_sheet_cells().

**Comment by yorkz1994** [comment]
Got your point.
Because it is nice to use `sheet_name` instead of `sheet_index` to operate, but `read_sheet` only take index, could you please consider providing a `read_sheet_by_name` function or make `find_sheet_index_by_name` public.

**Comment by MathNya** [comment]
@yorkz1994 
The latest version is released. 
read_sheet_by_name() is provided.

**Comment by yorkz1994** [comment]
Excellent!
