### ISSUE TITLE
Merged cells clash with `set_auto_width`

### ISSUE THREAD

**Issue by MGlolenstine** [MathNya/umya-spreadsheet#23]
After playing with the new update for a bit, I've noticed that the `set_auto_width` resizes the column to fit the first cell of the horizontally merged cell.

Behaviour:
![image](https://user-images.githubusercontent.com/9406770/152340543-26da427d-08f5-4684-9087-91cc92e41b7e.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/9406770/152340597-b4f95e4f-a181-483c-a87e-d526aace39b8.png)

I think that the column isn't calculating for merged cells and just checks what text is in it and it grabs that one.

Any further ideas would be much appreciated.

**Comment by MathNya** [comment]
Hi, MGlolenstine.

Thank you for your report.
Oh, I didn't take into account the merging of cells in auto_width.
We will address this in the next update.

In the current version, the width can be set manually.

**Comment by MathNya** [comment]
Apparently, it is very difficult to calculate the width taking into account the merged cells.
In the next update, auto_width will be disabled for columns with merged cells, just like Excel and other Spreadsheet libraries.
Please set the width of the relevant column manually.

**Comment by MGlolenstine** [comment]
I see that is fair.
I didn't know that Excel and other spreadsheet libraries disabled that auto-width.

I will have to set the widths manually, as I'm restricted to the width of the page.

Thanks for working on this!
