### ISSUE TITLE
Cannot handle multple fonts in same cell correctly

### ISSUE THREAD

**Issue by piaoger** [MathNya/umya-spreadsheet#232]
- How to reproduce

1.  create a file with two cells which are filled by mixing different Bold, Italic, Font and font size.  See attached aaa_multifonts.xlsx.
2. run a simple read write roundtrip
3. Open the output file, you will find fonts are not handled well for entire string.
   See below snapshot in WPS office, the 2nd and 3th chars are default Simsun。In MS Office, they are Calibri.
![1728116907586](https://github.com/user-attachments/assets/073cc7e1-7edb-471f-85f2-b7efd8dd3232)
![image](https://github.com/user-attachments/assets/eefedba8-af0c-4df2-93ba-8a777938dc88)

- code snippt
```rust
        let f = "/w/assets/xlsx/aaa_multifonts.xlsx";
        let path = std::path::Path::new(&f);
        let mut book = umya_spreadsheet::reader::xlsx::lazy_read(&path).unwrap();
        let _ = umya_spreadsheet::writer::xlsx::write(&book, &format!("{f}.rw.output.xlsx"));
```

 
[aaa_multifonts.xlsx](https://github.com/user-attachments/files/17405631/aaa_multifonts.xlsx)

[aaa_multifonts.xlsx.rw.output.xlsx](https://github.com/user-attachments/files/17265562/aaa_multifonts.xlsx.rw.output.xlsx)

**Comment by MathNya** [comment]
@piaoger 
Thank you very much for your help here.
I think it is probably a glitch.
We will investigate the cause and take action.

**Comment by MathNya** [comment]
@piaoger 
Sorry, could you please provide us with aaa_multifonts.xlsx so that we can understand the situation as accurately as possible.
(I think the two files you attached are probably both post-processed files.)
