### ISSUE TITLE
Image::get_image_data may panic

### ISSUE THREAD

**Issue by schungx** [MathNya/umya-spreadsheet#235]
If the image is a drawing with only shapes and no bitmaps, then `Image::get_image_data` will panic.

There doesn't appear to be an easy way to detect this case.  Suggest returning an `Option`.

**Comment by MathNya** [comment]
Thank you for your report.
We will address this in the next update.

**Comment by MathNya** [comment]
@schungx 
Since we want to avoid as much destructive modification as possible, we return empty if the image data does not exist.
The existence of image data can be checked with has_image().
