### ISSUE TITLE
super slow

### ISSUE THREAD

**Issue by cstkingkey** [MathNya/umya-spreadsheet#24]
when writing data to about 6000 cells, it took about 15min. The cpu usage is very high.

**Comment by MathNya** [comment]
Thank you for your report.
We will look into improving the efficiency of the writing process.
Please wait for our next update.

**Comment by cstkingkey** [comment]
> Thank you for your report. We will look into improving the efficiency of the writing process. Please wait for our next update.

reading is super slow too. An xlsx file about 240kb with about 30 sheets, reading a sheet contains 50 cells took about 10min too.

**Comment by cstkingkey** [comment]
It seems that this crate will read whole workkbook, rather than the used sheet.
And It will create a whole new workbook when saving rather than save the modified part.

At least, reading part can be changed to read sheets lazily.

**Comment by MathNya** [comment]
First of all, we reviewed the load-bearing processes without making major changes to the configuration.
We will update it sequentially for further speed improvement.

**Comment by cstkingkey** [comment]
> First of all, we reviewed the load-bearing processes without making major changes to the configuration. We will update it sequentially for further speed improvement.

Thanks for your excellent work and speedy response.
With latest version, the read time drops from 35s to 30s.

**Comment by MathNya** [comment]
Thank you for the quick confirmation.
We will aim to implement lazy loading as the next measure to improve processing speed.
