### ISSUE TITLE
get_cell returns None if not in cell_collection yet

### ISSUE THREAD

**Issue by ice1080** [MathNya/umya-spreadsheet#246]
Hello!
Fantastic library, we've loved using this so far.

I was trying to copy some cell styling from one row to another by writing our own method(s), and noticed that `worksheet.get_cell` returns `None` for cells that technically exist in the workbook but haven't been initialized to the `cell_collection` yet. This seemed a bit odd to me, as I was trying to duplicate a row by inserting a row and then copying the styling from the original cell-by-cell. It failed once it got to cells that didn't have any styling or values because they weren't in the `cell_collection`. 
I wanted to check if this was intentional or not. We can easily work around this by only copying the styling if the cell exists, or by using `get_cell_mut` which creates the cell under the hood if it doesn't exist. I'm assuming that this is in place to keep memory footprint low, but wanted to mention in case it was unknown. If intentional, please feel free to close this issue out. Thanks! (Might be helpful to add a line or two to the documentation explaining why a cell might exist but return `None` from `get_cell`)

Here's my sample code if easier to see :
```rust
    pub fn duplicate_row_with_styling<T>(
        &mut self,
        source_row_index: T,
        target_row_index: T,
        start_col: T,
        end_col: T,
    ) -> Result<()>
    where
        T: Into<u32> + Copy,
    {
        self.get_current_sheet()?
            .insert_new_row(&target_row_index.into(), &1);
        self.copy_row_styling(source_row_index, target_row_index, start_col, end_col)?;
        Ok(())
    }

    pub fn copy_row_styling<T>(
        &mut self,
        source_row_index: T,
        target_row_index: T,
        start_col: T,
        end_col: T,
    ) -> Result<()>
    where
        T: Into<u32> + Copy,
    {
        for i in start_col.into()..=end_col.into() {
            self.copy_cell_styling(
                CellCoordinates::from((i, source_row_index.into())),
                CellCoordinates::from((i, target_row_index.into())),
            )?;
        }
        Ok(())
    }

    pub fn copy_cell_styling(
        &mut self,
        source: CellCoordinates,
        target: CellCoordinates,
    ) -> Result<()> {
        let source_cell = self
            .get_current_sheet()?
            .get_cell(source)
            .ok_or(anyhow!("Cell not found!"))?;
        let source_style = source_cell.get_style().clone();
        let target_cell = self.get_current_sheet()?.get_cell_mut(target);
        target_cell.set_style(source_style);
        Ok(())
    }
```

**Comment by MathNya** [comment]
@ice1080 
Thank you for contacting us.

Yes, I am aware of the problem. Cells without values and styles are None.
Due to the structure of the Excel file, this implementation was easier.
Also, umya-spreadsheet is a situation that uses a lot of memory, so we do not plan to change this.
I will add a comment where appropriate.

I will also implement a function to copy the styles based on the sample code you provided.

**Comment by schungx** [comment]
I have wanted this for ages! A function to simply copy a row to another with all styles.  This would be tremendously useful.

Now if only we get the same for columns...

**Comment by ice1080** [comment]
Thanks for responding @MathNya !
Makes total sense, I figured memory was the primary reason for this and also for not wanting to return a new Cell instance from this. Just wanting to confirm, and ya a comment or note in the docs could help reduce questions like this. Feel free to close this issue out.

**Comment by MathNya** [comment]
@ice1080 
The latest version has been released.
New functions copy_row_styling(),copy_col_styling() are available.
Please try them out.
```rust
let mut book = umya_spreadsheet::reader::xlsx::read(path).unwrap();
let sheet = book.get_sheet_mut(&0).unwrap();
sheet.copy_row_styling(&3, &5, None, None);
sheet.copy_col_styling(&3, &5, None, None);
```

**Comment by schungx** [comment]
> @ice1080 The latest version has been released. New functions copy_row_styling(),copy_col_styling() are available. Please try them out.

Tried the new APIs and they seem to work perfectly!

This is so great for scenarios where I have a "template" row and need to copy to further rows to fill with data.

**Comment by ice1080** [comment]
We also tested today and saw these functions working on v2.2.0. Thanks @MathNya
