### ISSUE TITLE
write strategy

### ISSUE THREAD

**Issue by cstkingkey** [MathNya/umya-spreadsheet#26]
It shall operate the content in memory and then write all content into file.
Currently panic in writing process will lead to a corrupt file.

**Comment by MathNya** [comment]
Thank you for your report on this as well.

In case of panic, I think the correct move would be to not update the file.
We will address this issue in the next version update.

**Comment by MathNya** [comment]
Fixed a glitch.
Please use the latest version.

**Comment by cstkingkey** [comment]
thanks for your excellent work.
