### ISSUE TITLE
lazy load lead to corruption

### ISSUE THREAD

**Issue by cstkingkey** [MathNya/umya-spreadsheet#29]
when using lazy reading, the saved file can not open by ms office.
Files directly created by this crate have no such issue.
Related to unsupported features?

**Comment by MathNya** [comment]
We have designed the system to ignore any unsupported features even if they are retained.
Perhaps there is a defect in the write process.

What unsupported functions are you using?
What error messages do you get when you open an Excel file?
Please describe the situation to the best of your ability.

**Comment by cstkingkey** [comment]
the main difference is first one having data validation applied.

**Comment by MathNya** [comment]
Hmmm, it appears that the cause is not due to data validation.
I could not reproduce the error.
We will continue to investigate.

**Comment by cstkingkey** [comment]
I think simple way to fix this is keeping all files in the zip archive and replacing target file during write process if target file exists.

**Comment by MathNya** [comment]
Thank you for the information.
We were able to reproduce the problem here as well.
We will address this issue in the next update.

**Comment by MathNya** [comment]
The program has been corrected.
Please obtain and review the latest version.

**Comment by cstkingkey** [comment]
table content is lost with latest version.
tested under macOS with wps.

**Comment by MathNya** [comment]
Improved accuracy of lazy read.
Please get the latest version and check it.
