### ISSUE TITLE
Issues with writing file

### ISSUE THREAD

**Issue by SpyrosRoum** [MathNya/umya-spreadsheet#3]
After having written around 11k rows, when the time comes to save the file it freezes and the it spams "something else" to the console.
I went through my code and I don't ever print "something else", also I added a print just before `    umya_spreadsheet::writer::xlsx::write(&out_book, path).expect("Failed to write file to disk");`
My line gets printed, then it freezes and then is spams "something else"

Any idea what might be wrong?

**Comment by SpyrosRoum** [comment]
Update: The issue appears to be [here](https://github.com/MathNya/umya-spreadsheet/blob/c195e24cd549feb655fdfde656c1aaa3b6ad2aa9/src/writer/xlsx/worksheet.rs#L242)
I edited the line to see what `c.get_data_type()` returns, and it looks like it returns `n`, which after looking at Cell.rs, it looks like it is for numeric.

Does that mean that the library does not support writing numbers yet?

**Comment by MathNya** [comment]
Thanks for the report and investigation of the cause.
I'm sorry. It seems that the implementation was insufficient for the pointed out part.
We will fix it in the near future.

**Comment by MathNya** [comment]
This case has been dealt with. Please check with the latest version.

**Comment by SpyrosRoum** [comment]
Thanks for the quick fixes!
