### ISSUE TITLE
[Request] update doc to include example reading image in cell

### ISSUE THREAD

**Issue by wellitecho** [MathNya/umya-spreadsheet#35]
In the readme, it's mentioned that umya-spreadsheet can read and edit images in cell(albeit __still might be inconvenient__).
I looked into Image and found *get_image_data* to return a &Vec\<u8\>, but didn't know how to write this vec to a valid image file(with the right format).
Could you give an example in the readme?

Thanks in advance.

**Comment by MathNya** [comment]
Thank you for contacting us.
We have found some issues with loading images.
We will resolve this issue in our next update and will provide a method of implementation.

**Comment by MathNya** [comment]
Added functions related to image manipulation.
Please check here.
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Image.html

**Comment by wellitecho** [comment]
Thanks for the update. However , how may I access an image located at a specific cell, say, at the first sheet, x row, y col? This is the use case in my mind.

**Comment by MathNya** [comment]
Thank you for contacting us.
I see. If that is the case, I will prepare a method to retrieve the image that exists in the specified cell.
This will be addressed in the next update.

**Comment by MathNya** [comment]
Several functions are provided to retrieve images.

Please check here.
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Image.html
