### ISSUE TITLE
Lack of enum use

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#43]
I'm curious-- how come strings are often used in place of enums in this crate?
For example, cell types: https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Cell.html

Is it because all sorts of types are possible, the constants are just common ones?
In which case, why not do this?:
```rust
enum CellType {
  String,
  Numeric,
  Boolean,
  Formula,
  Null,
  Error,
  Other(String),
}
```

**Comment by KyGost** [comment]
Here's an example:
https://github.com/KyGost/multisql/blob/main/src/data/value/mod.rs#L63

**Comment by MathNya** [comment]
We apologize for any inconvenience.
For the initially developed parts, enum is not used.
(Recently developed parts use enum.)

We will try to switch over gradually.

**Comment by MathNya** [comment]
cstkingkey, Thank you always.
I will use it as a reference.

**Comment by KyGost** [comment]
> We apologize for any inconvenience. For the initially developed parts, enum is not used. (Recently developed parts use enum.)
> 
> We will try to switch over gradually.

Never any need to apologise! Thank you very much for both this awesome library and the way you respond to feedback!

**Comment by MathNya** [comment]
Based on #48 pull request, we have updated the relevant section.
Please contact us if you have any suggestions.
If not, we will close this page after a certain period of time.

**Comment by KyGost** [comment]
Haven't checked the solution but will trust that this issue is resolved.
