### ISSUE TITLE
"Title" and "Name" are used interchangably

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#44]
This method refers to sheet name:
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Spreadsheet.html#method.get_sheet_by_name

While this one refers to sheet title:
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Worksheet.html#method.get_title

Ideally only one of the two terms should be used

**Comment by MathNya** [comment]
I will try to unify with Name.
(since that is what vba was).
Title is deprecated and will be discontinued in 1.0.0.

**Comment by MathNya** [comment]
We have unified it here.
Spreadsheet::get_name()

https://github.com/MathNya/umya-spreadsheet/blob/5e59501e8f2da176e58860df75e5a9bef603f6f6/src/structs/worksheet.rs#L1393
