### ISSUE TITLE
`Spreadsheet::remove_row` and similar should be implemented on `Worksheet`

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#45]
https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Spreadsheet.html#method.remove_row
Is currently a `Spreadsheet` method. Surely it should be either also, or soley, implemented on `Worksheet`.

**Comment by KyGost** [comment]
Same with `remove_column`, `insert_new...`, etc.

**Comment by MathNya** [comment]
You are right.
I too wonder why it was not prepared in Worksheet.
We will address this in the next update.
