### ISSUE TITLE
avoid unnecessary Into<String>

### ISSUE THREAD

**Issue by cstkingkey** [MathNya/umya-spreadsheet#49]
some function require Into\<String\> but only reference it.

a: Into\<String\> then b = a.as_ref();

**Comment by MathNya** [comment]
Indeed, Into<String> is unnecessary.
We will switch to &str in turn.

**Comment by MathNya** [comment]
Removed unnecessary Into<String>.
Basically, it is now used only in setter, add, and new functions.
