### ISSUE TITLE
Read cell with number format

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [MathNya/umya-spreadsheet#5]
How may we read a cell's value in it's formatted form?

 For example, expected value is: `"49,046,881.12"` , what is returned is: `"49046881.119999997"`

```
let val = book.get_sheet(0)
            .unwrap()
            .get_cell("H2")
            .unwrap()
            .get_value();
```

**Comment by MathNya** [comment]
sorry. It's not yet implemented.
It will be implemented at the next update.

**Comment by MathNya** [comment]
Sorry I made you wait.
Implemented formatted value.
```rust
book.get_sheet(0).unwrap().get_formatted_value("A1");
```

It may still contain many bugs.
If you find a bug, please contact us.

**Comment by CharlesOkwuagwu** [comment]
Hi, Please how do you set a format?

**Comment by MathNya** [comment]
Use Excel to format the cells.

Currently, this program has no implementation to set the format.
We will support it in the next update in the near future.

**Comment by MathNya** [comment]
We prepared the set_format_code().

Code example
```rust
let _ = book.get_sheet_by_name_mut("Sheet1").unwrap().get_cell_mut("A1")
.set_value("49046881.119999997");

let _ = book.get_sheet_by_name_mut("Sheet1").unwrap().get_style_mut("A1")
.get_number_format_mut().set_format_code(umya_spreadsheet::NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED1); // #,##0.00

let value =  book.get_sheet_by_name_mut("Sheet1").unwrap().get_formatted_value("A1");
dbg!(&value); // 49,046,881.12
```
