### ISSUE TITLE
Sheet1 exists by default

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#55]
Is there a way to make it so that "Sheet1" isn't created by default?..
I figure this might be a limitation where at least 1 sheet is required. But it would be great if this weren't needed.

**Comment by MathNya** [comment]
At least one worksheet must be at least one worksheet to be able to open it in Excel.

For those who will add more worksheets later
We can provide a function to generate a new spreadsheet that does not contain a worksheet.

**Comment by KyGost** [comment]
> For those who will add more worksheets later We can provide a function to generate a new spreadsheet that does not contain a worksheet.

That would be great!

**Comment by MathNya** [comment]
We have prepared it here.
https://github.com/MathNya/umya-spreadsheet/blob/5e59501e8f2da176e58860df75e5a9bef603f6f6/src/lib.rs#L157-L173

**Comment by KyGost** [comment]
Working well, thanks!
