### ISSUE TITLE
Slow to read

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#56]
I've just tested umya via MultiSQL by selecting 100,000 rows from a CSV (not using umya) file into an XLSX (umya), and I've found that:

Writing files is plenty fast, finished in ~1s.
Reading the 100K row CSV takes >1s.
Reading the 100K row XLSX takes **>5m** (I gave up). Pins the CPU on 1 core at a time.

Hopefully this is something we can improve.

**Comment by ubamrein** [comment]
Just wondering, was this on a release build or a develop build?
I've experienced (e.g. with the `image` crate) that the oob-checks and overflow checks slow down array operations drastically.
So I had like factors of 1000x improvements between release and debug builds.

**Comment by KyGost** [comment]
A bench build (which enables optimisations)

**Comment by KyGost** [comment]
Yup, a release build.

**Comment by MathNya** [comment]
Improved processing speed.
Please contact us if it is still slow.
We will consider further improvement.

**Comment by KyGost** [comment]
Nice! Glad to hear.
The most optimisation possible would be desired. I'll check how it performs now and see how noticeable it is.

**Comment by KyGost** [comment]
Unfortunately I don't have the same dataset as I was testing with but it seems ***much*** better now.

Thanks!

**Comment by KyGost** [comment]
Oops... I ran the CSV one twice...

**Comment by KyGost** [comment]
Much better nonetheless.
