### ISSUE TITLE
[Meta] Place to converse

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#58]
Do you have somewhere to converse, like a discord?

**Comment by MathNya** [comment]
I will have a Gitter for you in the near future.
I will contact you again when it is ready.

**Comment by MathNya** [comment]
Chat space is available.
https://gitter.im/MathNya/umya-spreadsheet

**Comment by KyGost** [comment]
Thanks!

Looks like that has been linked to the README too, great.
