### ISSUE TITLE
`Spreadsheet::read_sheet_by_name` or `Worksheet::read`

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#59]
When initialising lazily, one must initialise a sheet in order to interact with it.
Currently that requires sheet index.

**Comment by cstkingkey** [comment]
use get_sheet_by_name_mut(sheetname)

**Comment by KyGost** [comment]
Doesn't initialise it

**Comment by KyGost** [comment]
> I guess you were using non-mut version

Nope
```rust
pub(crate) fn get_sheet_mut(&mut self, sheet_name: &str) -> Result<&mut Worksheet> {
  self.book
	.get_sheet_by_name_mut(sheet_name)
	.map_err(|_| SheetStorageError::FailedToGetSheet.into())
}
```

**Comment by MathNya** [comment]
I have checked the relevant sources and cannot find the cause.
Can you tell us where the panic occurred?

**Comment by KyGost** [comment]
I'll see if I can make a better, more comprehensive example later, but for now, this:
```rust
reader::xlsx::read_lazy
get_sheet_by_name_mut
get_cell_by_column_and_row_mut
set_value
writer::xlsx::write
```

**Comment by MathNya** [comment]
Sorry it took so long to respond.
I tried the above procedure with the latest version and did not encounter any errors.
Please check again with the latest version.
