### ISSUE TITLE
Integration test files are not available

### ISSUE THREAD

**Issue by ajmorgan** [MathNya/umya-spreadsheet#6]
Hi, 

I'm excited about your project!  Can you make your test files available?  It looks like they are located on your C drive in C:/spread_test_data/... (from integration_test.rs).

Thank you in advance,
Adam M

**Comment by MathNya** [comment]
Thank you for contacting me.
I have attached the test files.

Sincerely,

[spread_test_data.zip](https://github.com/MathNya/umya-spreadsheet/files/6285612/spread_test_data.zip)

**Comment by ajmorgan** [comment]
Thank you!
