### ISSUE TITLE
Opening, saving and closing file in LibreOffice Calc causes issues

### ISSUE THREAD

**Issue by KyGost** [MathNya/umya-spreadsheet#60]
I tried opening, saving and closing a sheet in LibreOffice Calc and tried to open the file again and got:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', .../src/structs/vml/spreadsheet/anchor.rs:152:30
```

**Comment by MathNya** [comment]
It appears that an unexpected parameter has been registered when saving a file in LibreOffice.
This will be corrected so that the error does not occur.

**Comment by MathNya** [comment]
We have resolved the event you indicated.
Please check after obtaining the latest version.

**Comment by KyGost** [comment]
Awesome!
Will check at some point.
Will close for now.
