### ISSUE TITLE
fix return for get_mut functions

### ISSUE THREAD

**Issue by alex13sh** [MathNya/umya-spreadsheet#66]
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L38
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L51
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L64
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L77
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L90
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L103
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L116
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L129
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L142
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/series_axis.rs#L155

https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L30
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L43
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L56
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L69
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L82
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L95
https://github.com/MathNya/umya-spreadsheet/blob/5b6b037a81b48813760ffd6161f330a5ef3e5158/src/structs/drawing/charts/data_labels.rs#L108

**Comment by MathNya** [comment]
Thank you for your report.
We will respond as soon as possible.
