### ISSUE TITLE
A part of a border settings of a merged cell are lost

### ISSUE THREAD

**Issue by usagi** [MathNya/umya-spreadsheet#67]
## Repro

1. Create a test input.xlsx file using Excel that has:
  - (a) a merged cell
  - (b) a borders of (a)
2. Read: `let book = umya_spreadsheet::reader::xlsx::read(Path::new("input.xlsx")).unwrap()`
3. Write: `umya_spreadsheet::writer::xlsx::write(&book, Path::new("output.xlsx")).unwrap()`

##### "input.xlsx"
![image](https://user-images.githubusercontent.com/115972/163787569-5ee35ee9-0bbb-4f53-b605-40355b3f5fac.png)

##### "output.xlsx"

![image](https://user-images.githubusercontent.com/115972/163787701-2858ee46-06f4-42f7-a8a6-4fffb065a6e1.png)

**Comment by MathNya** [comment]
I am not sure if it is due to the version of Excel or not, but I could not reproduce the event here.
If possible, we would appreciate an input.xlsx file.

**Comment by usagi** [comment]
It worked fine too with umya-spreadsheet- **0.7.0** and **19dddbf** (the latest git version)! I was test with umya-spreadsheet- **0.6.0** at the reporting. So sorry, thank you for resolving the issue.
