### ISSUE TITLE
Book layout level font settings are lost

### ISSUE THREAD

**Issue by usagi** [MathNya/umya-spreadsheet#68]
## Repro.

1. Create a test input.xlsx file using Excel that has:
  - (a) layout level font settings.
  - (b) some text in any cell. (Do **NOT** set the cell level font settings.)
2. Read: `let book = umya_spreadsheet::reader::xlsx::read(Path::new("input.xlsx")).unwrap()`
3. Write: `umya_spreadsheet::writer::xlsx::write(&book, Path::new("output.xlsx")).unwrap()`

### Font settings(set from layout settings) of **"input.xlsx"**

Set the layout level font settings.

![image](https://user-images.githubusercontent.com/115972/163792747-5e77e18c-9b51-4c65-80c7-51acd9fe6397.png)

* ↑: Menu -> "Page Layout" -> over the mouse cursor on "Fonts" of the "Themes" section of the menu ribbon.

![image](https://user-images.githubusercontent.com/115972/163792768-7c3c57b6-530b-4c71-b5c6-71158a96dca6.png)

* ↑: It applied the font settings from the layout settings. (It is **NOT** set from the cell level font settings.)

### Font settings(set from layout settings) of **"output.xlsx"**

Layout level font settings are lost.

![image](https://user-images.githubusercontent.com/115972/163793174-d0266b59-cba0-4080-83a8-e5f8030c5aba.png)

* ↑: Lost the layout level font settings and set the default of application level font settings.

![image](https://user-images.githubusercontent.com/115972/163793408-a6d9cf88-6af0-42cc-acdb-03a88cc20739.png)

* ↑: Lost the layout level font settings

**Comment by MathNya** [comment]
Thank you for your report here as well.
We will respond in due course.

**Comment by MathNya** [comment]
We have resolved the event you indicated.
Please check after obtaining the latest version.

**Comment by usagi** [comment]
I did a quick check on v0.7.1 to make sure it works. It is resolved. Thanks! 🎊
