### ISSUE TITLE
Does this aim to build an engine of spreadsheet application?

### ISSUE THREAD

**Issue by ImJeremyHe** [MathNya/umya-spreadsheet#75]
As it support reading and writing,

**Comment by MathNya** [comment]
Yes.
php has a phpspreadsheet, but rust did not have a similar one, so I made one.

**Comment by ImJeremyHe** [comment]
We do the same thing: https://github.com/proclml/LogiSheets

**Comment by MathNya** [comment]
Thank you for your referral.
The implementation of calculations and other features are not available in umya spreadsheet.
great works!!
