### ISSUE TITLE
Data lost in other cells of worksheet

### ISSUE THREAD

**Issue by pratik-mahamuni** [MathNya/umya-spreadsheet#77]
Thank you for this utility. Its very helpful.

I have facing this issue, where I have a template and I fill it with values using this library. When I write values into the concerned sheet, the sheet changes in weird ways. See picture. The sheet on the left hand is the template with no value in B3. Then I use the code below to write to B3 a float value. On the right hand most of my important formulas are gone (denoted by red lines). Not sure if I am using the library wrong.
```
    let template_path = Path::new("Template - Copy.xlsx");
    let filename: String = get_new_scorecard_filename(true, &mat_pathname)?;
    let mut book = match umya_spreadsheet::reader::xlsx::read(template_path) {
        Ok(book) => book,
        Err(_e) => return Err("Template spreadsheet could not be loaded".into()),
    };
    book.get_sheet_by_name_mut("Sheet1").unwrap()
        .get_cell_mut("B3")
        .set_value(bagwise["Cycle"][0].to_string());

    let _ = umya_spreadsheet::writer::xlsx::write(&book, filename);
```
![image](https://user-images.githubusercontent.com/64231439/189205120-131ec3f9-0ba8-46fb-9ce3-948f7938d555.png)

**Comment by MathNya** [comment]
Thank you for your report.
We have addressed this issue as soon as possible.
Version 0.8.1 has been released.
Please obtain this and check the operation.

**Comment by pratik-mahamuni** [comment]
@MathNya thank you for the quick update and release. I appreciate it. It works great. I tested it out on my use case and the issue no longer persists.

Another small issue that I found was the changing of fonts for the rows and column heads in the Excel document, and overriding fonts in random places where cells are written. Please see pictures. Let me know if you can fix that as well. Thank you.

![image](https://user-images.githubusercontent.com/64231439/189354396-d9985f51-7938-4bb3-8271-7368780d5599.png)
![image](https://user-images.githubusercontent.com/64231439/189354805-e8a4ac07-9077-4fc3-881a-91f3f0acc81b.png)

**Comment by MathNya** [comment]
@pratik-mahamuni Thank you for your confirmation.

We are currently investigating the issue regarding font settings.
We have not yet been able to reproduce the problem in our environment.
We will have to wait for a while before we can respond to the issue.

**Comment by pratik-mahamuni** [comment]
Thank you @MathNya. The original problem is addressed. Closing the issue.
