### ISSUE TITLE
`std::error:Error` is not implemented for `XlsxError` in `umya_spreadsheet::reader`, and `umya_spreadsheet::writer`

### ISSUE THREAD

**Issue by john-dc252** [MathNya/umya-spreadsheet#78]
I tried to use error propagation with `Box<dyn std::error::Error>` with the read and write methods
and found that `std::error::Error` was not implemented for `XlsxError`.

Is there a different preferred way of handling these errors or should `std::error::Error` be implemented for these?

**Comment by MathNya** [comment]
Thank you for contacting us.
Implemented std::error:Error in XlsxError.
Please get the latest version and check it.

**Comment by john-dc252** [comment]
Tested version `0.8.3` and error propagation with Box<dyn std::error::Error> is now possible. 
Thank you.
