### ISSUE TITLE
getting a value from a cell that has just one or more empty spaces returns a different value

### ISSUE THREAD

**Issue by nomad-rst** [MathNya/umya-spreadsheet#8]
when there is a cell that has only a white space (1+) when I try to get the value of that cell it doesn't return that empty space instead it return a value from a different cell (always the same one not a random one each time)

**Comment by MathNya** [comment]
Thank you for your report too.
This will also be fixed in the next update.

**Comment by MathNya** [comment]
We have updated the program to fix this bug.

**Comment by nomad-rst** [comment]
it is working now, thank you
