### ISSUE TITLE
structs::numbering_format::NumberingFormat issue

### ISSUE THREAD

**Issue by CataMark** [MathNya/umya-spreadsheet#81]
The following panics by default:

```
pub fn set_number_format_id(&mut self, value: u32) -> &mut Self {
  self.format_code = FILL_BUILT_IN_FORMAT_CODES
      .iter()
      .find_map(|(key, val)| {
          if key == &value {
              Some(val.clone())
          } else {
              panic!("Not Found NumberFormatId.") //this line should be None
          }
      })
      .unwrap();
  self.number_format_id = value;
  self.is_build_in = true;
  self
}
```

**Comment by MathNya** [comment]
Thank you for your report.
We will soon release a version that fixes the issues you have pointed out.

**Comment by MathNya** [comment]
Version 0.8.4, which fixes the problem, has been released.

**Comment by MathNya** [comment]
@fgimian 
Thank you for contacting us.
We will consider responding to this issue in version 3.0 or later, as the scope of impact is likely to be larger.

**Comment by fgimian** [comment]
> @fgimian 
> Thank you for contacting us.
> We will consider responding to this issue in version 3.0 or later, as the scope of impact is likely to be larger.

Awesome, thanks so much for all your hard work on this library!! 😊
