### ISSUE TITLE
The actual result of the line chart example is a stack line chart

### ISSUE THREAD

**Issue by xst-moons** [MathNya/umya-spreadsheet#89]
Hi, thanks for the greate job !

I refer to the code of the chart example. The line chart example actually shows a stack line chart, but I need a line chart. How can I draw an actual line chart?

line chart example :

![mmexport1672412097224](https://user-images.githubusercontent.com/104352954/210083681-6bcfa9a9-39f0-4a3e-9578-ba11c1018a3d.png)

excel line chart(what i need):
![mmexport1672412099796](https://user-images.githubusercontent.com/104352954/210083660-e254877c-831d-4c25-92f1-0a251da4c000.png)

**Comment by MathNya** [comment]
Thank you for contacting us.
We have a method to change to actual line chart.
After obtaining the latest version, please implement it as shown in the example below.

example (The bottom method is it.)
```rust
    let mut chart = umya_spreadsheet::structs::Chart::default();
    chart
        .new_chart(
            umya_spreadsheet::structs::ChartType::LineChart,
            from_marker,
            to_marker,
            area_chart_series_list,
        )
        .set_series_title(series_title_list)
        .set_series_point_title(series_point_title_list)
        .set_default_language("ja-JP")
        .set_title("Chart Title")
        .set_horizontal_title("Horizontal Title")
        .set_vertical_title("Vertical Title")
        .set_grouping(umya_spreadsheet::drawing::charts::GroupingValues::Standard);
```

**Comment by xst-moons** [comment]
The latest version has solved my problem well, thank you!
