### ISSUE TITLE
Conditional formatting is not applied correctly and can corrupt excel files.

### ISSUE THREAD

**Issue by ErnestasSku** [MathNya/umya-spreadsheet#90]
I noticed that after writing a file, the conditional styling would be disappear if it were expression type and would corrupt the file if it were "cellIs" type.  

```rust
    let a = book.get_sheet_by_name("...").unwrap();
    let b = a.get_conditional_styles_collection();
    println!("{:#?}", b);
```

running this code I noticed that the conditions would appear empty.

```rust
Conditional {
                condition_type: "cellIs",
                operator_type: "",
                ....
                stop_if_true: false,
                condition: [],
                cfvo_collection: [],
                style: Some(
                ....
```

version: 
umya-spreadsheet = "0.8.7"

**Comment by MathNya** [comment]
Thank you for your report.
We will investigate the cause of the problem and correct the program.

**Comment by MathNya** [comment]
The correction has been completed.
Please obtain the latest version and check again.

**Comment by ErnestasSku** [comment]
It seems to be working with the default formulas and the files no longer get corrupted. Anyways, wanted to let you know that I think this project is awesome. When I was looking at excel file manipulation with rust, I found stuff like "Only used for reading" library, or some other writing library which required to download LLVM iirc and do some extra stuff, which I thought was bothersome.
